
LIB=	crypto

SRCS=	b_dump.c bf_buff.c bf_lbuf.c bf_nbio.c bf_null.c bio_cb.c bio_err.c \
	bio_lib.c b_print.c buf_err.c buffer.c buf_str.c cryptlib.c err_bio.c \
	err.c err_def.c err_prn.c err_str.c lhash.c lh_stats.c sha1dgst.c \
	sha1_one.c sha256.c sha512.c sha_dgst.c sha_one.c

INCFLAGS= -I$(SRCDIR)/include -I$(SRCDIR)../dietlibc/include

include $(SRCDIR)../lib.mk
